ServerName _

<VirtualHost *:80>
    Header always unset Access-Control-Allow-Origin
    Header always unset Access-Control-Allow-Methods
    Header always unset Access-Control-Allow-Headers
    Header always unset Access-Control-Expose-Headers

    Header always set Access-Control-Allow-Origin "*"
    Header always set Access-Control-Allow-Methods "GET, OPTIONS"
    Header always set Access-Control-Allow-Headers "Content-Type, If-None-Match, If-Modified-Since, X-Requested-With, X-Signage-Agent"
    Header always set Access-Control-Expose-Headers "ETag, Last-Modified"

    # CORS preflight handling
    RewriteEngine On
    RewriteCond %{REQUEST_METHOD} =OPTIONS
    RewriteRule ^ - [R=204,L]

    # (Optional but often helpful) ensure Vary header is set
    Header always set Vary "Origin"

    ServerAdmin garlic@saghiadinos.de
    DocumentRoot "/var/www/public"
    <Directory "/var/www/public/">
        Options FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog /var/www/var/weblogs/error.log
    CustomLog /var/www/var/weblogs/access.log combined
</VirtualHost>
